package org.ytu.hr.frontend.addEmployeePage;

import org.ytu.hr.core.recruit.RecruitEmployee;
import org.ytu.hr.core.util.validators.bornDate.BornDateValidator;
import org.ytu.hr.core.util.validators.email.EmailValidator;
import org.ytu.hr.core.util.validators.name.NameValidator;
import org.ytu.hr.core.util.validators.TCKN.TCKNValidator;
import org.ytu.hr.core.util.validators.phoneNumber.PhoneNumberValidator;
import org.ytu.hr.core.util.validators.salary.SalaryValidator;
import org.ytu.hr.frontend.mainPage.MainPage;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Enumeration;

/**
 *
 * @author baselkelziye
 */
public class AddEmployePage extends javax.swing.JFrame {
    ButtonGroup group = new ButtonGroup();

    /**
     * Creates new form AddEmploye2Page
     */
    public AddEmployePage() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        dogumTarihiTextField.setText("GG-AA-YYYY");
        provinceComboBox.setSelectedItem("Adana");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        salaryTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        ErkekRadioButton = new javax.swing.JRadioButton();
        KadinRadioButton = new javax.swing.JRadioButton();
        DigerRadioButton = new javax.swing.JRadioButton();
        provinceLabel = new javax.swing.JLabel();
        districtLabel = new javax.swing.JLabel();
        TCLabel = new javax.swing.JLabel();
        TCTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        positionLabel = new javax.swing.JLabel();
        positionTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dogumTarihiTextField = new javax.swing.JFormattedTextField();
        provinceComboBox = new javax.swing.JComboBox<>();
        districtComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(236, 254, 255));

        jPanel2.setBackground(new java.awt.Color(246, 250, 255));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        confirmButton.setBorderPainted(false);
        confirmButton.setOpaque(true);
        confirmButton.setBackground(new java.awt.Color(51, 67, 100));
        confirmButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(244, 244, 244));
        confirmButton.setText("Onayla");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaylaButonuActionPerformed(evt);
            }
        });

        cancelButton.setBorderPainted(false);
        cancelButton.setOpaque(true);
        cancelButton.setBackground(new java.awt.Color(51, 67, 100));
        cancelButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(244, 244, 244));
        cancelButton.setText("İptal");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptalButonuActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(66, 76, 97));
        lastNameLabel.setText("Soyisim");

        emailLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(66, 76, 97));
        emailLabel.setText("E-Posta");

        genderLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(66, 76, 97));
        genderLabel.setText("Cinsiyet");

        adressLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        adressLabel.setForeground(new java.awt.Color(66, 76, 97));
        adressLabel.setText("Adres");

        salaryLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(66, 76, 97));
        salaryLabel.setText("Maaş");
        salaryLabel.setIconTextGap(0);

        ErkekRadioButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ErkekRadioButton.setText("Erkek");

        KadinRadioButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        KadinRadioButton.setText("Kadın");
        KadinRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KadinRadioButtonActionPerformed(evt);
            }
        });

        DigerRadioButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DigerRadioButton.setText("Diğer");


        group.add(ErkekRadioButton);
        group.add(KadinRadioButton);
        group.add(DigerRadioButton);

        provinceLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        provinceLabel.setForeground(new java.awt.Color(66, 76, 97));
        provinceLabel.setText("il");

        districtLabel.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        districtLabel.setForeground(new java.awt.Color(66, 76, 97));
        districtLabel.setText("ilçe");


        TCLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TCLabel.setForeground(new java.awt.Color(66, 76, 97));
        TCLabel.setText("TC Kimlik No");

        phoneNumberLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(66, 76, 97));
        phoneNumberLabel.setText("Telefon No");

        positionLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(66, 76, 97));
        positionLabel.setText("Pozisyon");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 76, 97));
        jLabel2.setText("İsim");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 76, 97));
        jLabel3.setText("Doğum Tarihi");

        dogumTarihiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogumTarihiTextFieldActionPerformed(evt);
            }
        });

        provinceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Iğdır", "Isparta", "İstanbul", "İzmir", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kilis", "Kırıkkale", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Şanlıurfa", "Siirt", "Sinop", "Sivas", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));
        provinceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilComboBoxActionPerformed(evt);
            }
        });

        districtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilceComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(provinceLabel))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(provinceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(districtLabel)
                                        .addComponent(districtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(positionLabel)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(TCLabel)
                                                                .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                                                                .addComponent(lastNameTextField)
                                                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(TCTextField)))
                                                .addContainerGap(12, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(positionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(salaryTextField)
                                                                .addComponent(adressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(phoneNumberTextField)
                                                                .addComponent(phoneNumberLabel)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addGap(76, 76, 76)
                                                                        .addComponent(ErkekRadioButton)
                                                                        .addGap(30, 30, 30)
                                                                        .addComponent(KadinRadioButton)
                                                                        .addGap(30, 30, 30)
                                                                        .addComponent(DigerRadioButton))
                                                                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel3)
                                                                .addComponent(dogumTarihiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TCLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderLabel)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ErkekRadioButton)
                                        .addComponent(KadinRadioButton)
                                        .addComponent(DigerRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dogumTarihiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(provinceLabel)
                                        .addComponent(districtLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(provinceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(districtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(positionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(confirmButton)
                                        .addComponent(cancelButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 76, 97));
        jLabel1.setText("Yeni Çalışan Bilgileri");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(341, 341, 341)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    private void ilComboBoxActionPerformed(ActionEvent evt) {

        if(provinceComboBox.getSelectedItem().equals("Adana")){
            districtComboBox.removeAllItems();
            districtComboBox.addItem("Aladağ");
            districtComboBox.addItem("Ceyhan");
            districtComboBox.addItem("Çukurova");
            districtComboBox.addItem("Feke");
            districtComboBox.addItem("İmamoğlu");
            districtComboBox.addItem("Karaisalı");
            districtComboBox.addItem("Karataş");
            districtComboBox.addItem("Kozan");
            districtComboBox.addItem("Pozantı");
            districtComboBox.addItem("Saimbeyli");
            districtComboBox.addItem("Sarıçam");
            districtComboBox.addItem("Seyhan");
            districtComboBox.addItem("Tufanbeyli");
            districtComboBox.addItem("Yumurtalık");
            districtComboBox.addItem("Yüreğir");
        }
        else if(provinceComboBox.getSelectedItem().equals("Adıyaman")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Adıyaman (İl merkezi)");
            districtComboBox.addItem("Besni");
            districtComboBox.addItem("Çelikhan");
            districtComboBox.addItem("Gerger");
            districtComboBox.addItem("Gölbaşı");
            districtComboBox.addItem("Kâhta");
            districtComboBox.addItem("Samsat");
            districtComboBox.addItem("Sincik");
            districtComboBox.addItem("Tut");

        }

        else if(provinceComboBox.getSelectedItem().equals("Afyonkarahisar")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Afyonkarahisar (İl merkezi)");
            districtComboBox.addItem("Başmakçı");
            districtComboBox.addItem("Bayat");
            districtComboBox.addItem("Bolvadin");
            districtComboBox.addItem("Çay");
            districtComboBox.addItem("Çobanlar");
            districtComboBox.addItem("Dazkırı");
            districtComboBox.addItem("Dinar");
            districtComboBox.addItem("Emirdağ");
            districtComboBox.addItem("Evciler");
            districtComboBox.addItem("Hocalar");
            districtComboBox.addItem("İhsaniye");
            districtComboBox.addItem("İscehisar");
            districtComboBox.addItem("Kızılören");
            districtComboBox.addItem("Sandıklı");
            districtComboBox.addItem("Sinanpaşa");
            districtComboBox.addItem("Sultandağı");
            districtComboBox.addItem("Şuhut");
        }
        else if(provinceComboBox.getSelectedItem().equals("Ağrı")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Ağrı (İl merkezi)");
            districtComboBox.addItem("Diyadin");
            districtComboBox.addItem("Doğubayazıt");
            districtComboBox.addItem("Eleşkirt");
            districtComboBox.addItem("Hamur");
            districtComboBox.addItem("Patnos");
            districtComboBox.addItem("Taşlıçay");
            districtComboBox.addItem("Tutak");
        }
        else if(provinceComboBox.getSelectedItem().equals("Aksaray")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Aksaray (İl merkezi)");
            districtComboBox.addItem("Ağaçören");
            districtComboBox.addItem("Eskil");
            districtComboBox.addItem("Gülağaç");
            districtComboBox.addItem("Güzelyurt");
            districtComboBox.addItem("Ortaköy");
            districtComboBox.addItem("Sarıyahşi");
            districtComboBox.addItem("Sultanhanı");
        }

        else if(provinceComboBox.getSelectedItem().equals("Amasya")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Amasya (İl merkezi)");
            districtComboBox.addItem("Göynücek");
            districtComboBox.addItem("Gümüşhacıköy");
            districtComboBox.addItem("Hamamözü");
            districtComboBox.addItem("Merzifon");
            districtComboBox.addItem("Suluova");
            districtComboBox.addItem("Taşova");
        }

        else if(provinceComboBox.getSelectedItem().equals("Ankara")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Akyurt");
            districtComboBox.addItem("Altındağ");
            districtComboBox.addItem("Ayaş");
            districtComboBox.addItem("Balâ");
            districtComboBox.addItem("Beypazarı");
            districtComboBox.addItem("Çamlıdere");
            districtComboBox.addItem("Çankaya");
            districtComboBox.addItem("Çubuk");
            districtComboBox.addItem("Elmadağ");
            districtComboBox.addItem("Etimesgut");
            districtComboBox.addItem("Evren");
            districtComboBox.addItem("Gölbaşı");
            districtComboBox.addItem("Güdül");
            districtComboBox.addItem("Haymana");
            districtComboBox.addItem("Kalecik");
            districtComboBox.addItem("Kahramankazan");
            districtComboBox.addItem("Keçiören");
            districtComboBox.addItem("Kızılcahamam");
            districtComboBox.addItem("Mamak");
            districtComboBox.addItem("Nallıhan");
            districtComboBox.addItem("Polatlı");
            districtComboBox.addItem("Pursaklar");
            districtComboBox.addItem("Sincan");
            districtComboBox.addItem("Şereflikoçhisar");
            districtComboBox.addItem("Yenimahalle");
        }

        else if(provinceComboBox.getSelectedItem().equals("Antalya")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Akseski");
            districtComboBox.addItem("Aksu");
            districtComboBox.addItem("Alanya");
            districtComboBox.addItem("Demre");
            districtComboBox.addItem("Döşemealtı");
            districtComboBox.addItem("Elmalı");
            districtComboBox.addItem("Finike");
            districtComboBox.addItem("Gazipaşa");
            districtComboBox.addItem("Gündoğmuş");
            districtComboBox.addItem("İbradı");
            districtComboBox.addItem("Kaş");
            districtComboBox.addItem("Gölbaşı");
            districtComboBox.addItem("Kemer");
            districtComboBox.addItem("Kepez");
            districtComboBox.addItem("Konyaaltı");
            districtComboBox.addItem("Korkuteli");
            districtComboBox.addItem("Kumluca");
            districtComboBox.addItem("Manavgat");
            districtComboBox.addItem("Muratpaşa");
            districtComboBox.addItem("Serik");
        }

        else if(provinceComboBox.getSelectedItem().equals("Ardahan")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Ardahan (İl merkezi)");
            districtComboBox.addItem("Çıldr");
            districtComboBox.addItem("Damal");
            districtComboBox.addItem("Göle");
            districtComboBox.addItem("Hanak");
            districtComboBox.addItem("Posof");
        }
        else if(provinceComboBox.getSelectedItem().equals("Artvin")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Artvin (İl merkezi)");
            districtComboBox.addItem("Ardanuç");
            districtComboBox.addItem("Arhavi");
            districtComboBox.addItem("Borçka");
            districtComboBox.addItem("Hopa");
            districtComboBox.addItem("Kemalpaşa");
            districtComboBox.addItem("Murgul");
            districtComboBox.addItem("Şavşat");
            districtComboBox.addItem("Yusufeli");
        }

        else if(provinceComboBox.getSelectedItem().equals("Aydın")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bozdoğan");
            districtComboBox.addItem("Buharkent");
            districtComboBox.addItem("Çine");
            districtComboBox.addItem("Didim");
            districtComboBox.addItem("Efeler");
            districtComboBox.addItem("Germencik");
            districtComboBox.addItem("İncirliova");
            districtComboBox.addItem("Karacasu");
            districtComboBox.addItem("Karpuzlu");
            districtComboBox.addItem("Koçarlı");
            districtComboBox.addItem("Köşk");
            districtComboBox.addItem("Kuşadası");
            districtComboBox.addItem("Kuyucak");
            districtComboBox.addItem("Nazilli");
            districtComboBox.addItem("Söke");
            districtComboBox.addItem("Sultanhisar");
            districtComboBox.addItem("Yenipazar");
        }

        else if(provinceComboBox.getSelectedItem().equals("Balıkesir")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Altıeylül");
            districtComboBox.addItem("Ayvalık");
            districtComboBox.addItem("Balya");
            districtComboBox.addItem("Bandırma");
            districtComboBox.addItem("Bigadiç");
            districtComboBox.addItem("Burhaniye");
            districtComboBox.addItem("Dursunbey");
            districtComboBox.addItem("Erdemit");
            districtComboBox.addItem("Erdek");
            districtComboBox.addItem("Gömeç");
            districtComboBox.addItem("Gönen");
            districtComboBox.addItem("Havran");
            districtComboBox.addItem("İvrindi");
            districtComboBox.addItem("Karesi");
            districtComboBox.addItem("Kepsut");
            districtComboBox.addItem("Manyas");
            districtComboBox.addItem("Marmara");
            districtComboBox.addItem("Savaştepe");
            districtComboBox.addItem("Sındırgı");
            districtComboBox.addItem("Susurluk");
        }

        else if(provinceComboBox.getSelectedItem().equals("Bartın")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bartın (İl merkezi)");
            districtComboBox.addItem("Amasra");
            districtComboBox.addItem("Kurucaşile");
            districtComboBox.addItem("Ulus");

        }

        else if(provinceComboBox.getSelectedItem().equals("Batman")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Batman (İl merkezi)");
            districtComboBox.addItem("Beşiri");
            districtComboBox.addItem("Gerçüş");
            districtComboBox.addItem("Hasankeyf");
            districtComboBox.addItem("Kozluk");
            districtComboBox.addItem("Sason");
        }

        else if(provinceComboBox.getSelectedItem().equals("Bayburt")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bayburt (İl merkezi)");
            districtComboBox.addItem("Aydıntepe");
            districtComboBox.addItem("Demirözü");
        }

        else if(provinceComboBox.getSelectedItem().equals("Bilecik")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bilecik (İl merkezi)");
            districtComboBox.addItem("Bozüyük");
            districtComboBox.addItem("Gölpazar");
            districtComboBox.addItem("İnhisr");
            districtComboBox.addItem("Osmaneli");
            districtComboBox.addItem("Pazaryeri");
            districtComboBox.addItem("Söğüt");
            districtComboBox.addItem("Yenipazar");
        }

        else if(provinceComboBox.getSelectedItem().equals("Bingöl")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bingöl (İl merkezi)");
            districtComboBox.addItem("Adaklı");
            districtComboBox.addItem("Genç");
            districtComboBox.addItem("Karlıova");
            districtComboBox.addItem("Kiğı");
            districtComboBox.addItem("Solhan");
            districtComboBox.addItem("Yayladere");
            districtComboBox.addItem("Yedisı");
        }

        else if(provinceComboBox.getSelectedItem().equals("Bitlis")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bitlis (İl merkezi)");
            districtComboBox.addItem("Adilcevaz");
            districtComboBox.addItem("Ahlat");
            districtComboBox.addItem("Güroymak");
            districtComboBox.addItem("Hizan");
            districtComboBox.addItem("Mutki");
            districtComboBox.addItem("Tatvan");
        }
        else if(provinceComboBox.getSelectedItem().equals("Bolu")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bolu (İl merkezi)");
            districtComboBox.addItem("Dörtdivan");
            districtComboBox.addItem("Gerede");
            districtComboBox.addItem("Göynük");
            districtComboBox.addItem("Kıbrıscık");
            districtComboBox.addItem("Mengen");
            districtComboBox.addItem("Mudurnu");
            districtComboBox.addItem("Seben");
            districtComboBox.addItem("Yeniçağa");
        }

        else if(provinceComboBox.getSelectedItem().equals("Burdur")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Burdur (İl merkezi)");
            districtComboBox.addItem("Ağlasun");
            districtComboBox.addItem("Altınyayla");
            districtComboBox.addItem("Bucak");
            districtComboBox.addItem("Çavdır");
            districtComboBox.addItem("Çeltikçi");
            districtComboBox.addItem("Gölhisar");
            districtComboBox.addItem("Karamanlı");
            districtComboBox.addItem("Kemer");
            districtComboBox.addItem("Tefenni");
            districtComboBox.addItem("Yeşilova");
        }
        else if(provinceComboBox.getSelectedItem().equals("Bursa")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Büyükırhan");
            districtComboBox.addItem("Gemlik");
            districtComboBox.addItem("Gürsu");
            districtComboBox.addItem("Harmancık");
            districtComboBox.addItem("İnegöl");
            districtComboBox.addItem("İznik");
            districtComboBox.addItem("Karacabey");
            districtComboBox.addItem("Keles");
            districtComboBox.addItem("Kestel");
            districtComboBox.addItem("Mudanya");
            districtComboBox.addItem("Mustafakemalpaşa");
            districtComboBox.addItem("Nilüfer");
            districtComboBox.addItem("Orhaneli");
            districtComboBox.addItem("Orhangazi");
            districtComboBox.addItem("Osmangazi");
            districtComboBox.addItem("Yenişehir");
            districtComboBox.addItem("Yıldırım");
        }

        else if(provinceComboBox.getSelectedItem().equals("Çanakkale")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Çanakkale (İl merkezi)");
            districtComboBox.addItem("Ayvacık");
            districtComboBox.addItem("Bayramiç");
            districtComboBox.addItem("Biga");
            districtComboBox.addItem("Bozcaada");
            districtComboBox.addItem("Çan");
            districtComboBox.addItem("Eceabat");
            districtComboBox.addItem("Ezine");
            districtComboBox.addItem("Gelibolu");
            districtComboBox.addItem("Gökçeada");
            districtComboBox.addItem("Lapseki");
            districtComboBox.addItem("Yenice");
        }

        else if(provinceComboBox.getSelectedItem().equals("Çankırı")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Çankırı (İl merkezi)");
            districtComboBox.addItem("Atkaracalar");
            districtComboBox.addItem("Bayramören");
            districtComboBox.addItem("Çerkeş");
            districtComboBox.addItem("Eldivan");
            districtComboBox.addItem("Ilgaz");
            districtComboBox.addItem("Kızılırmak");
            districtComboBox.addItem("Korgun");
            districtComboBox.addItem("Kurşunlu");
            districtComboBox.addItem("Orta");
            districtComboBox.addItem("Şabanözü");
            districtComboBox.addItem("Yapraklı");
        }

        else if(provinceComboBox.getSelectedItem().equals("Çorum")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Çorum (İl merkezi)");
            districtComboBox.addItem("Alaca");
            districtComboBox.addItem("Bayat");
            districtComboBox.addItem("Boğazkale");
            districtComboBox.addItem("Dodurga");
            districtComboBox.addItem("İskilip");
            districtComboBox.addItem("Kargı");
            districtComboBox.addItem("Laçin");
            districtComboBox.addItem("Mecitözü");
            districtComboBox.addItem("Oğuzlar");
            districtComboBox.addItem("Ortaköy");
            districtComboBox.addItem("Osmancık");
            districtComboBox.addItem("Sungurlu");
            districtComboBox.addItem("Uğurludağ");
        }

        else if(provinceComboBox.getSelectedItem().equals("Denizli")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Acıpayam");
            districtComboBox.addItem("Babadağ");
            districtComboBox.addItem("Baklan");
            districtComboBox.addItem("Bekilli");
            districtComboBox.addItem("Beyağaç");
            districtComboBox.addItem("Bozkurt");
            districtComboBox.addItem("Buldan");
            districtComboBox.addItem("Çal");
            districtComboBox.addItem("Çameli");
            districtComboBox.addItem("Çardak");
            districtComboBox.addItem("Çivril");
            districtComboBox.addItem("Güney");
            districtComboBox.addItem("Honaz");
            districtComboBox.addItem("Kale");
            districtComboBox.addItem("Merkezefendi");
            districtComboBox.addItem("Pamukkale");
            districtComboBox.addItem("Sarayköy");
            districtComboBox.addItem("Serinhisar");
            districtComboBox.addItem("Tavas");
        }

        else if(provinceComboBox.getSelectedItem().equals("Diyarbakır")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Bağlar");
            districtComboBox.addItem("Bismil");
            districtComboBox.addItem("Çermik");
            districtComboBox.addItem("Çınar");
            districtComboBox.addItem("Çüngüş");
            districtComboBox.addItem("Dicle");
            districtComboBox.addItem("Eğil");
            districtComboBox.addItem("Ergani");
            districtComboBox.addItem("Hani");
            districtComboBox.addItem("Hazro");
            districtComboBox.addItem("Kayapınar");
            districtComboBox.addItem("Kocaköy");
            districtComboBox.addItem("Kulp");
            districtComboBox.addItem("Lice");
            districtComboBox.addItem("Silvan");
            districtComboBox.addItem("Sur");
            districtComboBox.addItem("Yenişehir");
        }

        else if(provinceComboBox.getSelectedItem().equals("Düzce")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Düzce (İl merkezi)");
            districtComboBox.addItem("Akçakoca");
            districtComboBox.addItem("Cumayeri");
            districtComboBox.addItem("Çilimli");
            districtComboBox.addItem("Gölyaka");
            districtComboBox.addItem("Gümüşova");
            districtComboBox.addItem("Kaynaşlı");
            districtComboBox.addItem("Yığılca");
        }

        else if(provinceComboBox.getSelectedItem().equals("Edirne")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Edirne (İl merkezi)");
            districtComboBox.addItem("Enez");
            districtComboBox.addItem("Havsa");
            districtComboBox.addItem("İspala");
            districtComboBox.addItem("Keşan");
            districtComboBox.addItem("Lalapaşa");
            districtComboBox.addItem("Meriç");
            districtComboBox.addItem("Süloğlu");
            districtComboBox.addItem("Uzunköprü");
        }

        else if(provinceComboBox.getSelectedItem().equals("Elazığ")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Elazığ (İl merkezi)");
            districtComboBox.addItem("Ağın");
            districtComboBox.addItem("Alacakay");
            districtComboBox.addItem("Arıcak");
            districtComboBox.addItem("Baskil");
            districtComboBox.addItem("Karakoçan");
            districtComboBox.addItem("Keban");
            districtComboBox.addItem("Kovancılar");
            districtComboBox.addItem("Maden");
            districtComboBox.addItem("Palu");
            districtComboBox.addItem("Sivrice");
        }

        else if(provinceComboBox.getSelectedItem().equals("Erzincan")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Erzincan (İl merkezi)");
            districtComboBox.addItem("Çayırlı");
            districtComboBox.addItem("İliç");
            districtComboBox.addItem("Kemah");
            districtComboBox.addItem("Kemaliye");
            districtComboBox.addItem("Otlukbeli");
            districtComboBox.addItem("Refahiye");
            districtComboBox.addItem("Tercan");
            districtComboBox.addItem("Üzümlü");
        }

        else if(provinceComboBox.getSelectedItem().equals("Erzurum")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Aşkale");
            districtComboBox.addItem("Aziziye");
            districtComboBox.addItem("Çat");
            districtComboBox.addItem("Hınıs");
            districtComboBox.addItem("Horasan");
            districtComboBox.addItem("İspir");
            districtComboBox.addItem("Karaçoban");
            districtComboBox.addItem("Karayazı");
            districtComboBox.addItem("Köprüköy");

            districtComboBox.addItem("Narman");
            districtComboBox.addItem("Otlu");
            districtComboBox.addItem("Olur");
            districtComboBox.addItem("Palandöken");
            districtComboBox.addItem("Pasinler");
            districtComboBox.addItem("Pazaryolu");
            districtComboBox.addItem("Şenkaya");
            districtComboBox.addItem("Tekman");
            districtComboBox.addItem("Tortum");

            districtComboBox.addItem("Uzundere");
            districtComboBox.addItem("Yakutiye");
        }
        else if(provinceComboBox.getSelectedItem().equals("Eskişehir")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Alpu");
            districtComboBox.addItem("Beylikova");
            districtComboBox.addItem("Çifteler");
            districtComboBox.addItem("Günuüzü");
            districtComboBox.addItem("Han");
            districtComboBox.addItem("İnönü");
            districtComboBox.addItem("Mahmudiye");
            districtComboBox.addItem("Mihalgazi");
            districtComboBox.addItem("Mihalıççık");
            districtComboBox.addItem("Odunpazarı");
            districtComboBox.addItem("Sarıcakaya");
            districtComboBox.addItem("Seyitgazi");
            districtComboBox.addItem("Sivrihisar");
            districtComboBox.addItem("Tepebaşı");
        }

        else if(provinceComboBox.getSelectedItem().equals("Gaziantep")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Araban");
            districtComboBox.addItem("İslahiye");
            districtComboBox.addItem("Karkamış");
            districtComboBox.addItem("Nizip");
            districtComboBox.addItem("Nurdağı");
            districtComboBox.addItem("Oğuzeli");
            districtComboBox.addItem("Şahinbey");
            districtComboBox.addItem("Şehitkamil");
            districtComboBox.addItem("Yavuzeli");
        }

        else if(provinceComboBox.getSelectedItem().equals("Giresun")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Giresun (İl merkezi)");
            districtComboBox.addItem("Alacura");
            districtComboBox.addItem("Bulancak");
            districtComboBox.addItem("Çamoluk");
            districtComboBox.addItem("Çanakçı");
            districtComboBox.addItem("Dereli");
            districtComboBox.addItem("Doğankent");
            districtComboBox.addItem("Espiye");
            districtComboBox.addItem("Eynesil");
            districtComboBox.addItem("Görele");
            districtComboBox.addItem("Güce");
            districtComboBox.addItem("Keşap");
            districtComboBox.addItem("Piraziz");
            districtComboBox.addItem("Şebinkarahisar");
            districtComboBox.addItem("Tirebolu");
            districtComboBox.addItem("Yağlıdere");

        }

        else if(provinceComboBox.getSelectedItem().equals("Gümüşhane")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Gümüşhane (İl merkezi)");
            districtComboBox.addItem("Kelkit");
            districtComboBox.addItem("Köse");
            districtComboBox.addItem("Kürtün");
            districtComboBox.addItem("Şiran");
            districtComboBox.addItem("Torul");
        }

        else if(provinceComboBox.getSelectedItem().equals("Hakkâri")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Hakkâri (İl merkezi)");
            districtComboBox.addItem("Çukurca");
            districtComboBox.addItem("Derecik");
            districtComboBox.addItem("Şemdinli");
            districtComboBox.addItem("Yüksekova");
        }


        else if(provinceComboBox.getSelectedItem().equals("Hatay")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Altınözü");
            districtComboBox.addItem("Antakya");
            districtComboBox.addItem("Arsuz");
            districtComboBox.addItem("Belen");
            districtComboBox.addItem("Defne");
            districtComboBox.addItem("Dörtyol");
            districtComboBox.addItem("Erzin");
            districtComboBox.addItem("Hassa");
            districtComboBox.addItem("İskenderun");

            districtComboBox.addItem("Kırıkhan");
            districtComboBox.addItem("Kumlu");
            districtComboBox.addItem("Payas");
            districtComboBox.addItem("Reyhanlı");
            districtComboBox.addItem("Samandağ");
            districtComboBox.addItem("Yalyadağı");
        }

        else if(provinceComboBox.getSelectedItem().equals("Iğdır")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Iğdır (İl merkezi)");
            districtComboBox.addItem("Aralık");
            districtComboBox.addItem("Karakoyunlu");
            districtComboBox.addItem("Tuzluca");
        }

        else if(provinceComboBox.getSelectedItem().equals("Isparta")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Isparta (İl merkezi)");
            districtComboBox.addItem("Aksu");
            districtComboBox.addItem("Atabey");
            districtComboBox.addItem("Eğridir");
            districtComboBox.addItem("Gelendost");
            districtComboBox.addItem("Gönen");

            districtComboBox.addItem("Keçiborlu");
            districtComboBox.addItem("Senirkent");
            districtComboBox.addItem("Sütçüler");
            districtComboBox.addItem("Şarkikaraağaç");
            districtComboBox.addItem("Uluborlu");

            districtComboBox.addItem("Yalvaç");
            districtComboBox.addItem("Yenişarbademli");
        }

        else if(provinceComboBox.getSelectedItem().equals("İstanbul")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Adalr");
            districtComboBox.addItem("Arnavutköy");
            districtComboBox.addItem("Ataşehir");
            districtComboBox.addItem("Avcılar");
            districtComboBox.addItem("Bağcılar");
            districtComboBox.addItem("Bahçelievler");

            districtComboBox.addItem("Bakırköy");
            districtComboBox.addItem("Başakşehir");
            districtComboBox.addItem("Bayrampaşa");
            districtComboBox.addItem("Şarkikaraağaç");
            districtComboBox.addItem("Beşiktaş");
            districtComboBox.addItem("Beykoz");
            districtComboBox.addItem("Beylikdüzü");

            districtComboBox.addItem("Beyoğlu");
            districtComboBox.addItem("Büyükçekmece");
            districtComboBox.addItem("Çatalca");
            districtComboBox.addItem("Çekmeköy");
            districtComboBox.addItem("Esenler");
            districtComboBox.addItem("Esenyurt");
            districtComboBox.addItem("Eyüpsultan");
            districtComboBox.addItem("Fatih");
            districtComboBox.addItem("Gaziosmanpaşa");
            districtComboBox.addItem("Güngören");
            districtComboBox.addItem("Kadıköy");
            districtComboBox.addItem("Kâğıthane");
            districtComboBox.addItem("Kartal");


            districtComboBox.addItem("Küçükçekmece");
            districtComboBox.addItem("Maltepe");
            districtComboBox.addItem("Pendik");
            districtComboBox.addItem("Sancaktepe");
            districtComboBox.addItem("Sarıyer");
            districtComboBox.addItem("Silivri");
            districtComboBox.addItem("Sultanbeyli");
            districtComboBox.addItem("Sultangazi");
            districtComboBox.addItem("Şile");
            districtComboBox.addItem("Şişli");
            districtComboBox.addItem("Tuzla");
            districtComboBox.addItem("Ümraniye");
            districtComboBox.addItem("Üsküdar");
            districtComboBox.addItem("Zeytinburnu");
        }

        else if(provinceComboBox.getSelectedItem().equals("İzmir")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Aliağa");
            districtComboBox.addItem("Balçova");
            districtComboBox.addItem("Bayındır");
            districtComboBox.addItem("Bayraklı");
            districtComboBox.addItem("Bergama");
            districtComboBox.addItem("Beydağ");

            districtComboBox.addItem("Bornova");
            districtComboBox.addItem("Buca");
            districtComboBox.addItem("Çeşme");
            districtComboBox.addItem("Çiğli");
            districtComboBox.addItem("Dikili");
            districtComboBox.addItem("Foça");
            districtComboBox.addItem("Gaziemir");

            districtComboBox.addItem("Güzelbahçe");
            districtComboBox.addItem("Karabağlar");
            districtComboBox.addItem("Karaburun");
            districtComboBox.addItem("Karşıyaka");
            districtComboBox.addItem("Kemalpaşa");
            districtComboBox.addItem("Kınık");
            districtComboBox.addItem("Kiraz");
            districtComboBox.addItem("Konak");
            districtComboBox.addItem("Menderes");
            districtComboBox.addItem("Menemen");
            districtComboBox.addItem("Narlıdere");
            districtComboBox.addItem("Ödemiş");
            districtComboBox.addItem("Seferihisar");


            districtComboBox.addItem("Selçuk");
            districtComboBox.addItem("Tire");
            districtComboBox.addItem("Torbalı");
            districtComboBox.addItem("Urla");
        }

        else if(provinceComboBox.getSelectedItem().equals("Kahramanmaraş")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Afşin");
            districtComboBox.addItem("Andırın");
            districtComboBox.addItem("Çağlayancerit");
            districtComboBox.addItem("Dulkadiroğlu");
            districtComboBox.addItem("Ekinözü");
            districtComboBox.addItem("Elbistan");
            districtComboBox.addItem("Göksun");
            districtComboBox.addItem("Nurhak");
            districtComboBox.addItem("Onikişubat");
            districtComboBox.addItem("Pazarcık");
            districtComboBox.addItem("Türkoğlu");
        }

        else if(provinceComboBox.getSelectedItem().equals("Karabük")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Karabük (İl merkezi)");
            districtComboBox.addItem("Elfani");
            districtComboBox.addItem("Eskipazar");
            districtComboBox.addItem("Ovacık");
            districtComboBox.addItem("Safranbolu");
            districtComboBox.addItem("Yenice");
        }

        else if(provinceComboBox.getSelectedItem().equals("Karaman")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Karaman (İl merkezi)");
            districtComboBox.addItem("Ayrancı");
            districtComboBox.addItem("Başyayla");
            districtComboBox.addItem("Ermenek");
            districtComboBox.addItem("Kazımkarabekir");
            districtComboBox.addItem("Sarıveliler");
        }
        else if(provinceComboBox.getSelectedItem().equals("Kars")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Kars (İl merkezi)");
            districtComboBox.addItem("Akyaka");
            districtComboBox.addItem("Arpaçay");
            districtComboBox.addItem("Digor");
            districtComboBox.addItem("Kağızman");
            districtComboBox.addItem("Sarıkamış");
            districtComboBox.addItem("Selim");
            districtComboBox.addItem("Susuz");
        }
        else if(provinceComboBox.getSelectedItem().equals("Kastamonu")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Kastamonu (İl merkezi)");
            districtComboBox.addItem("Abana");
            districtComboBox.addItem("Ağlı");
            districtComboBox.addItem("Araç");
            districtComboBox.addItem("Azdavay");
            districtComboBox.addItem("Bozkurt");
            districtComboBox.addItem("Cide");
            districtComboBox.addItem("Çatalzeytin");

            districtComboBox.addItem("Daday");
            districtComboBox.addItem("Devrekani");
            districtComboBox.addItem("Doğanyurt");
            districtComboBox.addItem("Hanönü");
            districtComboBox.addItem("İhsangazi");
            districtComboBox.addItem("İnebolu");
            districtComboBox.addItem("Küre");
            districtComboBox.addItem("Pınarbaşı");

            districtComboBox.addItem("Seydiler");
            districtComboBox.addItem("Şenpazar");
            districtComboBox.addItem("Taşköprü");
            districtComboBox.addItem("Tosya");
        }

        else if(provinceComboBox.getSelectedItem().equals("Kayseri")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Akkışla");
            districtComboBox.addItem("Bünyan");
            districtComboBox.addItem("Develi");
            districtComboBox.addItem("Felahiye");
            districtComboBox.addItem("Hacılar");
            districtComboBox.addItem("İncesu");
            districtComboBox.addItem("Kocasinan");
            districtComboBox.addItem("Melikgazi");

            districtComboBox.addItem("Özvatan");
            districtComboBox.addItem("Pınarbaşı");
            districtComboBox.addItem("Sarıoğlan");
            districtComboBox.addItem("Sarız");
            districtComboBox.addItem("Talas");
            districtComboBox.addItem("Tomarza");
            districtComboBox.addItem("Yahyalı");
            districtComboBox.addItem("Yeşilhisar");

        }

        else if(provinceComboBox.getSelectedItem().equals("Kırkkale")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Kırkkale (İl merkezi)");
            districtComboBox.addItem("Bahşılı");
            districtComboBox.addItem("Çelebi");
            districtComboBox.addItem("Delice");
            districtComboBox.addItem("Karakeçili");
            districtComboBox.addItem("Keskin");
            districtComboBox.addItem("Sulakyurt");
            districtComboBox.addItem("Yahşihan");

        }

        else if(provinceComboBox.getSelectedItem().equals("Kırklareli")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Kırklareli (İl merkezi)");
            districtComboBox.addItem("Babaeski");
            districtComboBox.addItem("Demirköy");
            districtComboBox.addItem("Kofçaz");
            districtComboBox.addItem("Lüleburgaz");
            districtComboBox.addItem("Pehlivanköy");
            districtComboBox.addItem("Pınarhisar");
            districtComboBox.addItem("Vize");

        }

        else if(provinceComboBox.getSelectedItem().equals("Kırşehir")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Kırşehir (İl merkezi)");
            districtComboBox.addItem("Akçakent");
            districtComboBox.addItem("Akpınar");
            districtComboBox.addItem("Boztepe");
            districtComboBox.addItem("Çiçekdağı");
            districtComboBox.addItem("Kaman");
            districtComboBox.addItem("Mucur");
        }
        else if(provinceComboBox.getSelectedItem().equals("Kilis")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Kilis (İl merkezi)");
            districtComboBox.addItem("Elbeyli");
            districtComboBox.addItem("Musabeyli");
            districtComboBox.addItem("Polateli");
        }
        else if(provinceComboBox.getSelectedItem().equals("Kocaeli")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Başiskele");
            districtComboBox.addItem("Çayırova");
            districtComboBox.addItem("Darıca");
            districtComboBox.addItem("Derince");

            districtComboBox.addItem("Dilovası");
            districtComboBox.addItem("Gebze");
            districtComboBox.addItem("Gölcük");
            districtComboBox.addItem("İzmit");
        }

        else if(provinceComboBox.getSelectedItem().equals("Konya")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            districtComboBox.addItem("Ahırlı");
            districtComboBox.addItem("Akören");
            districtComboBox.addItem("Akşehir");
            districtComboBox.addItem("Altınekin");
            districtComboBox.addItem("Beyşehir");
            districtComboBox.addItem("Bozkır");
            districtComboBox.addItem("Cihanbeyli");
            districtComboBox.addItem("Çetlik");
            districtComboBox.addItem("Çumra");
            districtComboBox.addItem("Derbent");
            districtComboBox.addItem("Derebucak");
            districtComboBox.addItem("Doğanhisar");
            districtComboBox.addItem("Emirgazi");
            districtComboBox.addItem("Ereğli");
            districtComboBox.addItem("Güneysınır");
            districtComboBox.addItem("Hadim");

            districtComboBox.addItem("Halkpınar");
            districtComboBox.addItem("Hüyük");
            districtComboBox.addItem("Ilgın");
            districtComboBox.addItem("Kadınhanı");
            districtComboBox.addItem("Karapınar");
            districtComboBox.addItem("Karatay");
            districtComboBox.addItem("Kulu");
            districtComboBox.addItem("Meram");
            districtComboBox.addItem("Sarayönü");
            districtComboBox.addItem("Selçuklu");
            districtComboBox.addItem("Seydişehir");
            districtComboBox.addItem("Taşkent");
            districtComboBox.addItem("Tuzlukçu");
            districtComboBox.addItem("Yalıhüyük");
            districtComboBox.addItem("Yunak");

        }

        else if(provinceComboBox.getSelectedItem().equals("Kütahya")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Altıntaş", "Domaniç", "Dumlupınar", "Emet", "Gediz", "Merkez", "Pazarlar", "Simav", "Tavşanlı"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }

        else if(provinceComboBox.getSelectedItem().equals("Malatya")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Akçadağ", "Arapkır", "Arguvan", "Battalgazi", "Darende", "Doğanşehir", "Hekimhan", "Merkez", "Pötürge", "Yazıhan", "Yeşilhan"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }

        else if(provinceComboBox.getSelectedItem().equals("Manisa")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Ahmetli", "Akhisar", "Alaşehir", "Demirci", "Gölmarmara", "Gördes", "Kırkağaç", "Kula", "Merkez", "Salihli", "Sarıhanlı", "Soma", "Turgutlu"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }

        else if(provinceComboBox.getSelectedItem().equals("Mardin")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Derik", "Kızıltepe", "Mazıdağı", "Merkez", "Midyat", "Nusaybin", "Ömerli", "Savur"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }

        else if(provinceComboBox.getSelectedItem().equals("Mersin")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Anamur", "Bozyazı", "Çamlıyayla", "Erdemli", "Gülnar", "Merkez", "Mut", "Silifke", "Tarsus"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }

        else if(provinceComboBox.getSelectedItem().equals("Muğla")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Bodrum", "Datça", "Fathiye", "Kavaklıdere", "Köyceğiz", "Marmaris", "Merkez", "Milas", "Ortaca", "Ula", "Yatağan"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Muş")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Bulanık", "Korkut", "Malazgirt", "Merkez"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Nevşehir")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Merkez", "Ürgüp"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Niğde")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Altunhisar", "Bor", "Çamardı", "Çiftlik", "Ulukışla"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Ordu")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Akkuş", "Fatsa", "Görköy", "Kabadüz", "Merkez", "Mesudiye", "Perşembe", "Ulubey", "Ünye"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Osmaniye")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Bahçe", "Kadirli", "Merkez"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Rize")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Ardeşen", "Çayeli", "Fındıklı", "Merkez", "Pazar", "Çamlıhemşin"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Sakarya")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Akyazı", "Geyve", "Hendek", "Karasu", "Kaynarca", "Merkez", "Sapanca", "Taraklı"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Şanlıurfa")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Alaçam", "Bafra", "Çarşamba", "Havza", "Kavak", "Ladik", "Merkez", "Salıpazarı", "Tekkeköy", "Terme", "Vezirköprü"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Siirt")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Aydınlar", "Baykan", "Eruh", "Kurtalan", "Merkez"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Sinop")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Ayancık", "Boyabat", "Durağan", "Elfelek", "Gerze", "Merkez"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Şırnak")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Cizre", "İdil", "Merkez", "Silopi"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Sivas")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Altınyayla", "Divriği", "Doğansar", "Gemerek", "Hafik", "Kangal", "Merkez", "Şarkışla", "Suşehri", "Yılızeli", "Zara"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Tekirdağ")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Çerkezköy", "Çorlu", "Hayrabolu", "Malkara", "MarmaraEreğlisi", "Merkez", "Muratlı", "Saray", "Şarköy"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Tokat")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Almuz", "Erbaa", "Merkez", "Niksar", "Pazar", "Reşadiye", "Sulusaray", "Turhal", "Zile"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Trabzon")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Akçabat", "Araklı", "Arşin", "Beşikdüzü", "Çarşıbaşı", "Çaykara", "Dernekpazarı", "Maçka", "Merkez", "Of", "Sürmene", "Tonya", "Vakfıkebir", "Yomra"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Tunceli")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Çemişgezek", "Hozat", "Mazgirt", "Merkez", "Nazimiye", "Pertek"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Uşak")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Banaz", "Eşme", "Merkez", "Sivaslı", "Ulubey"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Van")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Başkale", "Çaldıran", "Çatak", "Erciş", "Gevaş", "Gürpınar", "Merkez", "Muradiye", "Özalp"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Yalova")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Altınova", "Armutlu", "Merkez"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Yozgat")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Boğazlıyan", "Çandır", "Çayıralan", "Merkez", "Sarıkaya", "Sefaatli", "Sorgun", "Yenifakili", "Yerköy"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
        else if(provinceComboBox.getSelectedItem().equals("Zonguldak")){
            districtComboBox.removeAllItems();
            districtComboBox.setSelectedItem(null);
            String[] items =  new String[]{"Araplı", "Çaycuma", "Devrek", "Ereğli", "Merkez"};
            for(String itm:items){
                districtComboBox.addItem(itm);
            }
        }
    }

    private void ilceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }



    private void KadinRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void iptalButonuActionPerformed(java.awt.event.ActionEvent evt) {

        if(evt.getSource() == this.cancelButton){
            // TODO add your handling code here:
            this.setVisible(false);
        }
    }

    private void onaylaButonuActionPerformed(java.awt.event.ActionEvent evt) {

        boolean isCorrect = true;

        String name = nameTextField.getText();
        if (! new NameValidator().validate(name)) {
            JOptionPane.showMessageDialog(null, "Geçersiz Bir İsim", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }
        String surname = lastNameTextField.getText();
        if (isCorrect && ! new NameValidator().validate(surname)) {
            JOptionPane.showMessageDialog(null, "Geçersiz Bir Soyisim", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;

        }
        String citizenID = TCTextField.getText();
        if (isCorrect &&! new TCKNValidator().validate(citizenID)) {
            JOptionPane.showMessageDialog(null, "Geçersiz Bir TC Kimlik Numarası", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }
        String email = emailTextField.getText();
        if (isCorrect &&! new EmailValidator().validate(email)) {
            JOptionPane.showMessageDialog(null, "Geçersiz Bir E-Posta Adresi", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;

        }
        String gender = getSelectedButtonText(group);
        if (isCorrect && gender == null) {
            JOptionPane.showMessageDialog(null, "Lütfen bir cinsiyet seçiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }
        String birthDateText = dogumTarihiTextField.getText();
        if (isCorrect &&! new BornDateValidator().validate(birthDateText)) {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir doğum tarihi giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }
        String phoneNumber = phoneNumberTextField.getText();
       if (isCorrect && ! new PhoneNumberValidator().validate(phoneNumber)) {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir telefon numarası giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }
        String salary = salaryTextField.getText();
        if (isCorrect &&! new SalaryValidator().validate(salary)) {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir maaş giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }

        String position = positionTextField.getText(); // Validation req
        if (isCorrect && ! new NameValidator().validate(position)) {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir pozisyon giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            isCorrect = false;
        }

        String district = (String) districtComboBox.getSelectedItem();
        String province = (String) provinceComboBox.getSelectedItem();
        if (isCorrect)
        {
            if(evt.getSource() == this.confirmButton){
                int res = RecruitEmployee.RecordEmployeeToDB(citizenID, phoneNumber, name, surname, email, gender, birthDateText,
                        new java.sql.Date(System.currentTimeMillis()).toString(), salary, position, province, district);
                if (res == -1)
                    MainPage.updatejTable1();
                else {
                    JOptionPane.showMessageDialog(null, "Eleman önceden sisteme eklenmiştir.", "Hata", JOptionPane.ERROR_MESSAGE);
                }
                this.setVisible(false);
            }
        }
    }

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void dogumTarihiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployePage().setVisible(true);
            }
        });
    }
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            JRadioButton button = (JRadioButton) buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton DigerRadioButton;
    private javax.swing.JRadioButton ErkekRadioButton;
    private javax.swing.JRadioButton KadinRadioButton;
    private javax.swing.JLabel TCLabel;
    private javax.swing.JTextField TCTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField dogumTarihiTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JComboBox<String> provinceComboBox;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JComboBox<String> districtComboBox;
    private javax.swing.JLabel districtLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField positionTextField;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    // End of variables declaration
}
