package org.ytu.hr.frontend.informationPage;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import org.ytu.hr.core.dayoff.DayOff;
import org.ytu.hr.core.models.employee.Employee;
import org.ytu.hr.core.recruit.RemoveEmployee;
import org.ytu.hr.core.util.employee.EmployeeUtil;
import org.ytu.hr.core.util.payment.Payment;
import org.ytu.hr.core.util.validators.name.NameValidator;
import org.ytu.hr.core.util.validators.phoneNumber.PhoneNumberValidator;
import org.ytu.hr.core.util.validators.salary.SalaryValidator;
import org.ytu.hr.frontend.dayOutPage.DayOutFrame;
import org.ytu.hr.frontend.mainPage.MainPage;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author baselkelziye
 */
public class InformationPage extends javax.swing.JFrame {
    private Employee employee;
    private boolean isAbsent;

    /**
     * Creates new form InformationPage
     */
    public InformationPage() {
        setEmployee(MainPage.selectedEmployee);
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        setTitle("ORAKLI");
    }
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameInfo = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameInfo = new javax.swing.JLabel();
        citizenIDLabel = new javax.swing.JLabel();
        citizenIDInfo = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailInfo = new javax.swing.JLabel();
        birthDateLabel = new javax.swing.JLabel();
        genderInfo = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        birthDathInfo = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        salaryTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        positionLabel = new javax.swing.JLabel();
        positionTextField = new javax.swing.JTextField();
        absentDayTextField = new javax.swing.JLabel();
        dayOffTextField = new javax.swing.JTextField();
        absentButton = new javax.swing.JButton();
        permessionedDaysLabel = new javax.swing.JLabel();
        permessionButton = new javax.swing.JButton();
        permessionedDaysTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        dayOffStartingLabel = new javax.swing.JLabel();
        dayOffEndingLabel = new javax.swing.JLabel();
        dayOffStartingTextField = new javax.swing.JTextField();
        dayOffEndingTextField = new javax.swing.JTextField();
        thisMonthSalaryLabetl = new javax.swing.JLabel();
        thisMonthSalaryTextField = new javax.swing.JTextField();

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(66, 76, 97));
        jLabel13.setText("Maaş:");

        jPanel1.setBackground(new java.awt.Color(236, 254, 255));

        headerLabel.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        headerLabel.setText("ÇALIŞAN BİLGİLERİ");

        jPanel2.setBackground(new java.awt.Color(246, 250, 255));

        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(66, 76, 97));
        nameLabel.setText("Isim:");

        nameInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        nameInfo.setText(employee.getFirstName());

        lastNameLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(66, 76, 97));
        lastNameLabel.setText("Soyisim:");

        lastNameInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lastNameInfo.setText(employee.getLastName());

        citizenIDLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        citizenIDLabel.setForeground(new java.awt.Color(66, 76, 97));
        citizenIDLabel.setText("TC Kimlik NO:");

        citizenIDInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        citizenIDInfo.setText(employee.getCitizenID() + "");

        emailLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(66, 76, 97));
        emailLabel.setText("E-Posta:");

        emailInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        emailInfo.setText(employee.getEmail());

        birthDateLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        birthDateLabel.setForeground(new java.awt.Color(66, 76, 97));
        birthDateLabel.setText("Doğum Tarihi:");

        genderInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        genderInfo.setText(employee.getGender());

        genderLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(66, 76, 97));
        genderLabel.setText("Cinsiyet:");

        birthDathInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        birthDathInfo.setText(employee.getBirthDate().toString());

        salaryLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(66, 76, 97));
        salaryLabel.setText("Maaş:");

        salaryTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        salaryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryTextFieldActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(66, 76, 97));
        addressLabel.setText("Adress:");

        addressTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addressTextField.setText(employee.getDistrict() + "/" + employee.getProvince());
        addressTextField.setEditable(false);

        phoneNumberLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(66, 76, 97));
        phoneNumberLabel.setText("Telefon No:");

        phoneNumberTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        phoneNumberTextField.setText(employee.getPhoneNumber() + "");
        phoneNumberTextField.setEditable(false);

        positionLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        positionLabel.setForeground(new java.awt.Color(66, 76, 97));
        positionLabel.setText("Pozisyon:");

        positionTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        positionTextField.setText(employee.getPosition());

        absentDayTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        absentDayTextField.setForeground(new java.awt.Color(66, 76, 97));
        absentDayTextField.setText("Gelmediği Gün Sayısı:");


        dayOffTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        dayOffEndingLabel.setText(employee.getPosition() + "/30");

        absentButton.setBackground(new java.awt.Color(51, 67, 100));
        absentButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        absentButton.setForeground(new java.awt.Color(244, 244, 244));
        absentButton.setText("Bugün İşe Gelmedi");
        absentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absentButtonActionPerformed(evt);
            }
        });

        permessionedDaysLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        permessionedDaysLabel.setForeground(new java.awt.Color(66, 76, 97));
        permessionedDaysLabel.setText("Kullanılan izin Sayısı:");

        permessionButton.setBackground(new java.awt.Color(51, 67, 100));
        permessionButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        permessionButton.setForeground(new java.awt.Color(244, 244, 244));
        permessionButton.setText("İzin Oluştur");
        permessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayOutActionPerformed(evt);
            }
        });

        permessionedDaysTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        confirmButton.setBackground(new java.awt.Color(51, 67, 100));
        confirmButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(244, 244, 244));
        confirmButton.setText("Kaydet");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        removeEmployeeButton.setBackground(new java.awt.Color(200, 67, 50));
        removeEmployeeButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        removeEmployeeButton.setForeground(new java.awt.Color(244, 244, 244));
        removeEmployeeButton.setText("Bu Çalışanı Sil");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        positionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionTextFieldActionPerformed(evt);
            }
        });

        dayOffStartingLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dayOffStartingLabel.setForeground(new java.awt.Color(66, 76, 97));
        dayOffStartingLabel.setText("İzin Başlangıcı:");

        dayOffEndingLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dayOffEndingLabel.setForeground(new java.awt.Color(66, 76, 97));
        dayOffEndingLabel.setText("İzin Bitişi:");

        thisMonthSalaryLabetl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        thisMonthSalaryLabetl.setForeground(new java.awt.Color(66, 76, 97));
        thisMonthSalaryLabetl.setText("Bu Ayın Maaşı:");

        dayOffTextField.setEditable(false);
        dayOffTextField.setText(employee.getAbsentDay() + "");


//        absentDayTextField.setEditable();

        salaryTextField.setText(employee.getSalary() + "");
        thisMonthSalaryTextField.setText(new Payment().reducedSalary(employee) + "");

        String tmp = "";
        if (employee.getPaid_leave_start() != null) {
            tmp = employee.getPaid_leave_start().toString();
            dayOffStartingTextField.setText(tmp);
        }
        if (employee.getPaid_leave_end() != null) {
            tmp = employee.getPaid_leave_end().toString();
            dayOffEndingTextField.setText(tmp);
        }
        permessionedDaysTextField.setText(employee.getPaidLeave() + "/30");
        permessionedDaysTextField.setEditable(false);
        dayOffStartingTextField.setEditable(false);
        dayOffEndingTextField.setEditable(false);
        thisMonthSalaryTextField.setEditable(false);



        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(citizenIDLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(citizenIDInfo)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(0, 30, Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(removeEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(156, 156, 156)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(dayOffEndingLabel)
                                                                                        .addComponent(dayOffEndingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(26, 26, 26))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(genderLabel)
                                                                        .addComponent(emailLabel)
                                                                        .addComponent(lastNameLabel))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(emailInfo)
                                                                        .addComponent(genderInfo)
                                                                        .addComponent(lastNameInfo)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                .addComponent(nameLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(nameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(dayOffStartingLabel)
                                                                        .addComponent(dayOffStartingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(permessionedDaysLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(permessionedDaysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(permessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(absentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap())
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(absentDayTextField)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(dayOffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                        .addComponent(phoneNumberLabel)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                        .addComponent(salaryLabel)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                        .addComponent(salaryTextField))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                        .addComponent(addressLabel)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(addressTextField))
                                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                        .addComponent(thisMonthSalaryLabetl)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(thisMonthSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGap(136, 136, 136))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(birthDateLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(birthDathInfo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(positionLabel)
                                                .addGap(26, 26, 26)
                                                .addComponent(positionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(136, 136, 136))
                                        .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(citizenIDInfo)
                                        .addComponent(citizenIDLabel)
                                        .addComponent(salaryLabel)
                                        .addComponent(salaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameInfo)
                                        .addComponent(nameLabel)
                                        .addComponent(thisMonthSalaryLabetl)
                                        .addComponent(thisMonthSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameInfo)
                                        .addComponent(lastNameLabel)
                                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addressLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailInfo)
                                        .addComponent(emailLabel)
                                        .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneNumberLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(genderLabel)
                                        .addComponent(genderInfo)
                                        .addComponent(dayOffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(absentDayTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(birthDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birthDathInfo)
                                        .addComponent(positionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(positionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dayOffStartingLabel)
                                                        .addComponent(dayOffEndingLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(absentButton)
                                                .addGap(17, 17, 17)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(permessionedDaysLabel)
                                        .addComponent(permessionedDaysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dayOffStartingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dayOffEndingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(removeEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(permessionButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(314, 314, 314)
                                                .addComponent(headerLabel))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(headerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void removeEmployeeButtonActionPerformed(ActionEvent evt) {
        JOptionPane.showMessageDialog(null,  new Payment().compensation(employee) +" TL tazminat ödenecektir.",
                "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        RemoveEmployee.RemoveEmployeeFromDB(employee.getEmployeeID());
        EmployeeUtil.getAllEmployees().remove(employee);
        MainPage.updatejTable1();
        this.setVisible(false);
    }


    private void salaryTextFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        int salary;
        try {
            salary = Integer.parseInt(salaryTextField.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir maaş giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (employee.getSalary() != salary)
            if (new SalaryValidator().validate(salaryTextField.getText())) {
                employee.setSalary(salary);
                thisMonthSalaryTextField.setText(new Payment().reducedSalary(employee) + "");
            }
        else {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir maaş giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        long phoneNumber = Long.parseLong(phoneNumberTextField.getText());
        if (employee.getPhoneNumber() != phoneNumber)
            if (new PhoneNumberValidator().validate("" + phoneNumber))
                employee.setPhoneNumber(phoneNumber);
            else {
                JOptionPane.showMessageDialog(null, "Lütfen geçerli bir telefon numarası giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
            }
    }
    private void positionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        String position = positionTextField.getText();
        if ((!employee.getPosition().equals(position))) {
            if (new NameValidator().validate(position))
                employee.setPosition(position);
            else {
                JOptionPane.showMessageDialog(null, "Lütfen geçerli bir pozisyon giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Ekrandaki bilgilerin sisteme kaydedilmesi
        System.out.println();
        EmployeeUtil.saveEmployee(employee);
        EmployeeUtil.updateEmployeeList(employee);
        MainPage.updatejTable1();

        this.setVisible(false);
    }
    private void absentButtonActionPerformed(java.awt.event.ActionEvent evt) { // AbssnetDay
        if (employee.isIs_absent()) {
            JOptionPane.showMessageDialog(null, "Bu kişi bugün izindedir.", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isAbsent) {
            DayOff.addAbsentDay(employee);
            dayOffTextField.setText("" + employee.getAbsentDay());
            thisMonthSalaryTextField.setText(new Payment().reducedSalary(employee) + "");
            isAbsent = true;
        } else {
            JOptionPane.showMessageDialog(null, "Bugün bu kişinin işe gelmediğini belirttiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void dayOutActionPerformed(java.awt.event.ActionEvent evt) {
        DayOutFrame dayOutFrame = new DayOutFrame();
        dayOutFrame.setInfoPage(this);
        dayOutFrame.setVisible(true);
    }
    public void updateDayOffs() {
        dayOffStartingTextField.setText(employee.getPaid_leave_start().toString());
        dayOffEndingTextField.setText(employee.getPaid_leave_end().toString());
        dayOffTextField.setText(employee.getPaidLeave() + "/30");
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationPage().setVisible(true);
            }
        });
    }

    private javax.swing.JButton absentButton;
    private javax.swing.JLabel absentDayTextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JLabel birthDathInfo;
    private javax.swing.JLabel citizenIDInfo;
    private javax.swing.JLabel citizenIDLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dayOffEndingLabel;
    private javax.swing.JTextField dayOffEndingTextField;
    private javax.swing.JLabel dayOffStartingLabel;
    private javax.swing.JTextField dayOffStartingTextField;
    private javax.swing.JTextField dayOffTextField;
    private javax.swing.JLabel emailInfo;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderInfo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameInfo;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel nameInfo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton permessionButton;
    private javax.swing.JLabel permessionedDaysLabel;
    private javax.swing.JTextField permessionedDaysTextField;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JTextField positionTextField;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JLabel thisMonthSalaryLabetl;
    private javax.swing.JTextField thisMonthSalaryTextField;
}