package org.ytu.hr.frontend.informationPage;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import org.ytu.hr.core.dayoff.DayOff;
import org.ytu.hr.core.models.employee.Employee;
import org.ytu.hr.core.recruit.RemoveEmployee;
import org.ytu.hr.core.util.employee.EmployeeUtil;
import org.ytu.hr.core.util.payment.Payment;
import org.ytu.hr.core.util.validators.name.NameValidator;
import org.ytu.hr.core.util.validators.phoneNumber.PhoneNumberValidator;
import org.ytu.hr.core.util.validators.salary.SalaryValidator;
import org.ytu.hr.frontend.dayOutPage.DayOutFrame;
import org.ytu.hr.frontend.mainPage.MainPage;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author baselkelziye
 */
public class InformationPage extends javax.swing.JFrame {
    private Employee employee;
    private boolean isAbsent;

    /**
     * Creates new form InformationPage
     */
    public InformationPage() {
        setEmployee(MainPage.selectedEmployee);
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jLabel13 = new JLabel();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        nameLabel = new JLabel();
        jLabel2 = new JLabel();
        surnameLabel = new JLabel();
        jLabel4 = new JLabel();
        citizenIDLabel = new JLabel();
        jLabel6 = new JLabel();
        emailLabel = new JLabel();
        jLabel8 = new JLabel();
        genderLabel = new JLabel();
        jLabel10 = new JLabel();
        birthDateLabel = new JLabel();
        jLabel12 = new JLabel();
        salaryTextField = new JTextField();
        jLabel14 = new JLabel();
        adressTextField = new JTextField();
        jLabel15 = new JLabel();
        phoneNumberTextField = new JTextField();
        jLabel16 = new JLabel();
        positionTextField = new JTextField();
        jLabel18 = new JLabel();
        absentDayTextField = new JTextField();
        absentButton = new JButton();
        jLabel21 = new JLabel();
        dayOffButton = new JButton();
        dayOffTextField = new JTextField();
        confirmButton = new JButton();
        removeEmployeeButton = new JButton();
        jLabel3 = new JLabel();
        jLabel5 = new JLabel();
        dayoffEndingTextField = new JTextField();
        dayOffStartingTextField = new JTextField();
        jLabel20 = new JLabel();
        jButton3 = new JButton();

        dayOffStartingTextField.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        dayOffStartingTextField.setForeground(new Color(66, 76, 97));
        String tmp;
        if (employee.getPaid_leave_end() != null) {
            dayOffStartingTextField.setText(employee.getPaid_leave_end().toString());
        }
        dayOffStartingTextField.setEditable(false);

        dayoffEndingTextField.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        dayoffEndingTextField.setForeground(new Color(66, 76, 97));
        if (employee.getPaid_leave_start() != null) {
            dayoffEndingTextField.setText(employee.getPaid_leave_start().toString());
        }
        dayoffEndingTextField.setEditable(false);

        jLabel13.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new Color(66, 76, 97));
        jLabel13.setText("Maaş:");

        jPanel1.setBackground(new Color(236, 254, 255));

        jPanel2.setBackground(new Color(246, 250, 255));

        jLabel1.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new Color(66, 76, 97));
        jLabel1.setText("Isim:");

        nameLabel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        nameLabel.setText(employee.getFirstName());

        jLabel2.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new Color(66, 76, 97));
        jLabel2.setText("Soyisim:");

        surnameLabel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        surnameLabel.setText(employee.getLastName());

        jLabel4.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new Color(66, 76, 97));
        jLabel4.setText("TC Kimlik NO:");

        citizenIDLabel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        citizenIDLabel.setText(String.valueOf(employee.getCitizenID()));

        jLabel6.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new Color(66, 76, 97));
        jLabel6.setText("E-Posta:");

        emailLabel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        emailLabel.setText(employee.getEmail());

        jLabel8.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new Color(66, 76, 97));
        jLabel8.setText("Doğum Tarihi:");

        birthDateLabel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        birthDateLabel.setText(employee.getBirthDate().toString());


        jLabel10.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new Color(66, 76, 97));
        jLabel10.setText("Cinsiyet:");

        genderLabel.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        genderLabel.setText(employee.getGender());

        jLabel12.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new Color(66, 76, 97));
        jLabel12.setText("Maaş:");

        salaryTextField.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        salaryTextField.setText(String.valueOf(employee.getSalary()));
        salaryTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                salaryTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new Color(66, 76, 97));
        jLabel14.setText("Adress:");

        adressTextField.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        adressTextField.setText(employee.getDistrict() + "/" + employee.getProvince());
        adressTextField.setEditable(false);

        jLabel15.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new Color(66, 76, 97));
        jLabel15.setText("Telefon No:");

        phoneNumberTextField.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        phoneNumberTextField.setText("" + employee.getPhoneNumber());
        phoneNumberTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new Color(66, 76, 97));
        jLabel16.setText("Pozisyon:");

        positionTextField.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        positionTextField.setText(employee.getPosition());
        positionTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                positionTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new Color(66, 76, 97));
        jLabel18.setText("Gelmediği Gün Sayısı:");

        absentDayTextField.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        absentDayTextField.setText("" + employee.getAbsentDay());
        absentDayTextField.setEditable(false);

        absentButton.setBackground(new Color(51, 67, 100));
        absentButton.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        absentButton.setForeground(new Color(244, 244, 244));
        absentButton.setText("Bugün İşe Gelmedi");
        absentButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                absentButtonActionPerformed(evt);
            }
        });
        dayOffButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                dayOutActionPerformed(evt);
            }
        });


        jLabel21.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setForeground(new Color(66, 76, 97));
        jLabel21.setText("Kullanılan izin Sayısı:");

        dayOffButton.setBackground(new Color(51, 67, 100));
        dayOffButton.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        dayOffButton.setForeground(new Color(244, 244, 244));
        dayOffButton.setText("İzin Oluştur");

        dayOffTextField.setFont(new Font("Helvetica Neue", 1, 13)); // NOI18N
        dayOffTextField.setText(employee.getPaidLeave() + "/30");  // Izin Sayisi
        dayOffTextField.setEditable(false);

        confirmButton.setBackground(new Color(51, 67, 100));
        confirmButton.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        confirmButton.setForeground(new Color(244, 244, 244));
        confirmButton.setText("Kaydet");

        confirmButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        removeEmployeeButton.setBackground(new Color(200, 67, 50));
        removeEmployeeButton.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        removeEmployeeButton.setForeground(new Color(244, 244, 244));
        removeEmployeeButton.setText("Bu Çalışanı Sil");
        removeEmployeeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new Color(66, 76, 97));
        jLabel3.setText("İzin Başlangıcı:");

        jLabel5.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new Color(66, 76, 97));
        jLabel5.setText("İzin Bitişi:");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(confirmButton, GroupLayout.PREFERRED_SIZE, 614, GroupLayout.PREFERRED_SIZE)
                                                .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(removeEmployeeButton, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jLabel21)
                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(dayOffTextField, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(dayOffButton, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(absentButton, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(dayoffEndingTextField, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(36, 36, 36)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(dayOffStartingTextField, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jLabel5)))
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(birthDateLabel)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel16)
                                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(positionTextField, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel18)
                                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(absentDayTextField, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel4)
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(citizenIDLabel))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(genderLabel))
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel6)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(emailLabel))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel2)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(surnameLabel))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(nameLabel, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)))
                                                                                .addGap(79, 79, 79)
                                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel15)
                                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(phoneNumberTextField, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jLabel14)
                                                                                                        .addComponent(jLabel12))
                                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(salaryTextField, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(adressTextField, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))))))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(9, 9, 9)))
                                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(citizenIDLabel)))
                                                .addGap(5, 5, 5)
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jLabel1))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(9, 9, 9)
                                                                .addComponent(nameLabel)))
                                                .addGap(3, 3, 3))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(salaryTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)))
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jLabel2))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(surnameLabel)))
                                                .addGap(3, 3, 3)
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jLabel6))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(emailLabel)))
                                                .addGap(3, 3, 3))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel14)
                                                        .addComponent(adressTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15)
                                                        .addComponent(phoneNumberTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(2, 2, 2)))
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel10))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(genderLabel)
                                                        .addComponent(jLabel16)
                                                        .addComponent(positionTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(birthDateLabel)
                                        .addComponent(jLabel18)
                                        .addComponent(absentDayTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(absentButton)
                                                .addGap(9, 9, 9))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(dayOffTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                .addComponent(dayOffStartingTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dayoffEndingTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel21))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(removeEmployeeButton)
                                        .addComponent(dayOffButton))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmButton, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        jLabel20.setFont(new Font("SansSerif", 1, 16)); // NOI18N
        jLabel20.setText("ÇALIŞAN BİLGİLERİ");

        jButton3.setBackground(new Color(51, 67, 100));
        jButton3.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setForeground(new Color(244, 244, 244));
        jButton3.setText("İzin Oluştur");
        jButton3.setVisible(false);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(78, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(337, 337, 337))
                                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73))))
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(286, 286, 286)
                                        .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 268, GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(287, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addComponent(jButton3)
                                        .addContainerGap(185, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    private void removeEmployeeButtonActionPerformed(ActionEvent evt) {
        JOptionPane.showMessageDialog(null,  new Payment().compensation(employee) +"kadar tazminat ödenecektir.",
                "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        RemoveEmployee.RemoveEmployeeFromDB(employee.getEmployeeID());
        EmployeeUtil.getAllEmployees().remove(employee);
        MainPage.updatejTable1();
        this.setVisible(false);
    }


    private void salaryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        int salary = Integer.parseInt(salaryTextField.getText());
        if (employee.getSalary() != salary)
        if (new SalaryValidator().validate("" + salary))
            employee.setSalary(salary);
        else {
            JOptionPane.showMessageDialog(null, "Lütfen geçerli bir maaş giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        long phoneNumber = Long.parseLong(phoneNumberTextField.getText());
        if (employee.getPhoneNumber() != phoneNumber)
            if (new PhoneNumberValidator().validate("" + phoneNumber))
                employee.setPhoneNumber(phoneNumber);
            else {
                JOptionPane.showMessageDialog(null, "Lütfen geçerli bir telefon numarası giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
            }
    }
    private void positionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maasTextFieldActionPerformed
        String position = positionTextField.getText();
        if ((!employee.getPosition().equals(position))) {
            if (new NameValidator().validate(position))
                employee.setPosition(position);
            else {
                JOptionPane.showMessageDialog(null, "Lütfen geçerli bir pozisyon giriniz", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Ekrandaki bilgilerin sisteme kaydedilmesi
        System.out.println();
        EmployeeUtil.saveEmployee(employee);
        EmployeeUtil.updateEmployeeList(employee);
        MainPage.updatejTable1();

        this.setVisible(false);
    }
    private void absentButtonActionPerformed(java.awt.event.ActionEvent evt) { // AbssnetDay
        if (!isAbsent) {
            DayOff.addAbsentDay(employee);
            absentDayTextField.setText("" + employee.getAbsentDay());
            isAbsent = true;
        } else {
            JOptionPane.showMessageDialog(null, "Bugün bu kişinin işe gelmediğini belirttiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void dayOutActionPerformed(java.awt.event.ActionEvent evt) {
        // İzin alma ekranının girilmesi.
        DayOutFrame dayOutFrame = new DayOutFrame();
        dayOutFrame.setInfoPage(this);
        dayOutFrame.setVisible(true);
    }
    public void updateDayOffs() {
        dayoffEndingTextField.setText(employee.getPaid_leave_start().toString());
        dayOffStartingTextField.setText(employee.getPaid_leave_end().toString());
        dayOffTextField.setText(employee.getPaidLeave() + "/30");
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JTextField adressTextField;
    private javax.swing.JButton absentButton;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField absentDayTextField;
    private javax.swing.JTextField dayoffEndingTextField;
    private javax.swing.JTextField dayOffStartingTextField;
    private javax.swing.JButton dayOffButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField dayOffTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField salaryTextField;
    private javax.swing.JTextField positionTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel citizenIDLabel;
    private javax.swing.JTextField phoneNumberTextField;
    // End of variables declaration
    // End of variables declaration
    // End of variables declaration//GEN-END:variables
}